### PR TITLE
Update missing pieces list

### PR DESCRIPTION
**Pull request by shinzui**
I updated the doc following this [discourse](https://discuss.ocaml.org/t/advantages-of-ocaml-over-rust/2112/36) suggestion.

### CODE REVIEW

**Comment by pmetzger** [comment]
Looks good. My only complaint is that your text is way, way wider than 80 columns, which makes dealing with the markdown later harder. Please try to put in line breaks where appropriate and re-push, and then I'll merge this.

**Comment by bluddy** [comment]
@pmetzger we should add the 80 columns width recommendation to contributing.md.

**Comment by bluddy** [comment]
Although 80 chars is a little harsh. I'm going to merge this and then fix it up.

**Comment by pmetzger** [comment]
@bluddy It's very hard to comment on merge requests etc. when the patch lines cover whole paragraphs. Remember this doesn't alter how the web site looks, only the markdown source code we read.

**Comment by bluddy** [comment]
Fair enough. Let's come up with a number that's > 80 though.

**Comment by pmetzger** [comment]
Why >80? When I open my Emacs window, that's how wide it is. That's the case for a lot of people...

**Comment by shinzui** [comment]
Sorry. I did it from the github UI instead of vim so I didn't notice the width. FWIW I use 120 instead of 80.

**Comment by pmetzger** [comment]
The lowest common denominator is 80, so I think we should stick to that. (It also starts getting hard for many people to read lines of text when they're too wide.)

**Pull request merged**
