### PR TITLE
Add Concurrency and Parallelism with OCaml

### PR DESCRIPTION
**Pull request by omasanori**

### CODE REVIEW

**Comment by gasche** [comment]
Drive-by feedback: I always prefer text documents to videos; when you point to a URL, could you add (video) in the description when it is actually a video, so that I know to prefer non-video links?

**Comment by omasanori** [comment]
> Drive-by feedback: I always prefer text documents to videos; when you point to a URL, could you add (video) in the description when it is actually a video, so that I know to prefer non-video links?

Agreed. I will add the indicator and add links to conference papers or slides if they are published. Thanks for feedback, @gasche !

**Comment by gasche** [comment]
Thanks! Another drive-by comment: I see that you have extended your PR with some extra topics to discuss. I would recommend instead to get the PR merged with the initial scope of things you wanted to discuss, and then send a follow-up PR with extra material if you wish to. Smaller PRs are easier to review, and my impression of ocamlverse is that it is more of a wiki were faster iterations (and less perfectionism on each change) are the default.

**Comment by omasanori** [comment]
> Another drive-by comment: I see that you have extended your PR with some extra topics to discuss. I would recommend instead to get the PR merged with the initial scope of things you wanted to discuss, and then send a follow-up PR with extra material if you wish to. Smaller PRs are easier to review, and my impression of ocamlverse is that it is more of a wiki were faster iterations (and less perfectionism on each change) are the default.

Indeed. I will do so. Thanks!

**Pull request merged**
