### PR TITLE
Add ALPN

### PR DESCRIPTION
**Pull request by 314eter**

### CODE REVIEW

**Comment by bluddy** [comment]
Thanks!

**Comment by pmetzger** [comment]
I don't think we should have merged this. It's a pointer to pull requests, not to a package a user will be able to use...

**Comment by 314eter** [comment]
It's explicitly mentioned that HTTP2 is not supported yet, and that it's a list of ongoing work. For someone looking for the status of HTTP2 in OCaml (maybe interested to contribute) this is useful information.

**Comment by bluddy** [comment]
Eh... normally I'd agree that we should have only links to projects in the ecosystem. I think we can make a small exception temporarily for this. HTTP2 is very high priority for the community, and pointing people to the relevant places makes sense, I think. Let's just keep this up to date so we don't end up linking to old PRs.

Another example I can think of is the lwt PR for httpaf, which is super high priority for the community but has yet to be merged. I wouldn't mind directing people there to bug the maintainer :yum:

**Pull request merged**
