### PR TITLE
PG'OCaml has siûpport for both camlp4 and ppx

### PR DESCRIPTION
**Pull request by Et7f3**

### CODE REVIEW

**Comment by bluddy** [comment]
Thanks!

**Comment by pmetzger** [comment]
@bluddy I can't really parse the new version of this text; it makes no sense to me. Maybe it should have been made clearer before committing?

**Comment by bluddy** [comment]
I do think it could be clarified, and I just clarified it in the latest version. Thanks for the comment.

**Comment by Et7f3** [comment]
if you want to edit: https://opam.ocaml.org/packages/pgocaml_ppx/ the link to the ppx.

**Comment by Et7f3** [comment]
> I can't really parse the new version of this text; it makes no sense to me. Maybe it should have been made clearer before committing?
@pmetzger ? Is what I wrote valid english ?

**Pull request merged**
