### PR TITLE
Add sidebar with TOC and site by tags

### PR DESCRIPTION
**Pull request by bluddy**
I've tagged every post and created jekyll code to collect the tags and display them on the side. I also incorporated a jekyll TOC. You can view the demo [here](https://bluddy.github.io/ocamlverse.github.io)

The CSS sucks, I know. I'm not great at making it look good, and perhaps will merge this first and then let other people help fix it up.

Also, the links on the sidebar for the site are broken, but they won't be once we merge it in.

### CODE REVIEW

**Comment by pmetzger** [comment]
A bunch of this looks wrong to me when I view it in Chrome:

image

**Comment by bluddy** [comment]
OK @pmetzger , I fixed that problem -- it's a CSS issue when zoomed in.

There are still CSS issues, but they can be fixed later.

**Comment by pmetzger** [comment]
Hrm. Now it's worse, the sidebar isn't on the side any more!

**Comment by bluddy** [comment]
OK I've stabilized it. I'm going to merge. It's good enough, and hopefully we can improve it with time.

**Pull request merged**
